name: Release

on:
  release:
    types: [created]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Check out the repository
      uses: actions/checkout@v2.3.3
      with:
        fetch-depth: 2

    - name: Set up Python
      uses: actions/setup-python@v2.1.2
      with:
        python-version: "3.x"
          
    - name: Upgrade pip
      run: |
        pip install --constraint=.github/workflows/constraints.txt pip
          
    - name: Install Poetry
      run: |
        pip install --constraint=.github/workflows/constraints.txt poetry

    - name: Build package
      run: |
        poetry build --ansi
    
    - name: Check if there is a parent commit
      id: check-parent-commit
      run: |
        echo "::set-output name=sha::$(git rev-parse --verify --quiet HEAD^)"
        
    - name: Detect and tag new version
      id: check-version
      if: steps.check-parent-commit.outputs.sha
      uses: salsify/action-detect-and-tag-new-version@v2.0.1
      with:
        version-command: |
          bash -o pipefail -c "poetry version | awk '{ print \$2 }'"
            
    - name: Bump version for developmental release
      if: "! steps.check-version.outputs.tag"
      run: |
        poetry version patch &&
        version=$(poetry version | awk '{ print $2 }') &&
        poetry version $version.dev.$(date +%s)

    - name: Publish package on PyPI
      uses: pypa/gh-action-pypi-publish@v1.3.1
      with:
        user: ${{ secrets.PYPI_USERNAME }}
        password: ${{ secrets.PYPI_PASSWORD }}
